// <auto-generated />
namespace Dota2Helper.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dota2helper : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dota2helper));
        
        string IMigrationMetadata.Id
        {
            get { return "201510141908212_dota2helper"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
